parameters:
    #MAILER
    mailer_transport: smtp
    mailer_user:      nadawca@enotekapergamin.pl
    mailer_password:  ~
    mailer_host:      enotekapergamin.pl

    mailer_from_mail:  nadawca@enotekapergamin.pl
    mailer_from_name:  Enoteka Pergamin

    #contact form
    contact_form_mail: dariusz.dziegiel@gmail.com

    #DB
    database_host: localhost
    database_port: null
    database_name: enoteka
    database_user: ~
    database_password: ~

    #facebook login
    facebook_client_id: ~
    facebook_client_secret: ~

    #google login
    google_client_id: ~
    google_client_secret: ~

    #google maps
    google_maps_api_key: ~