parameters:
    #MAILER
    mailer_transport: smtp
    mailer_user:      nadawca@enotekapergamin.pl
    mailer_password:  enoNAD1!
    mailer_host:      enotekapergamin.pl

    mailer_from_mail:  nadawca@enotekapergamin.pl
    mailer_from_name:  Enoteka Pergamin

    #contact form
    contact_form_mail: dariusz.dziegiel@gmail.com

    #DB
    database_host: localhost
    database_port: null
    database_name: enoteka
    database_user: root
    database_password: passwd

    #facebook login
    facebook_client_id: 123
    facebook_client_secret: 123

    #google login
    google_client_id: 123
    google_client_secret: 123

    #google maps
    google_maps_api_key: AIzaSyCJVuM9IplH7Ds-tU7ZxKI5MrAqxT2y4_8